#pragma once

#include "IAnimated.h"
#include "IBindable.h"
#include "IBlob.h"
#include "IColored.h"
#include "ILight.h"
#include "IModel.h"
#include "IMovable.h"
#include "IObject.h"
#include "IRotatable.h"
#include "IScalable.h"
#include "IShader.h"
#include "ISlot.h"
#include "ITexture2D.h"
#include "IToString.h"
#include "IShaderResourse.h"
