#pragma once

// Textures //
#define SLOT_TEXTURE_DIFFUSE 0
#define SLOT_TEXTURE_NORMALMAP 1
#define SLOT_TEXTURE_SPECULAR 2
#define SLOT_TEXTURE_HEIGHT 3
#define SLOT_TEXTURE_SPECULAR_COLORED 4

#define SLOT_TEXTURE2D_ARRAY_DIFFUSE 4
#define SLOT_TEXTURE2D_ARRAY_NORMALMAP 5
#define SLOT_TEXTURE2D_ARRAY_SPECULAR 6
#define SLOT_TEXTURE2D_ARRAY_HEIGHT 7

// Buffers //
#define SLOT_TRANSFORM_BUFFER 0
#define SLOT_MATERIAL_STRUCTURED_BUFFER 5
#define SLOT_SAMPLER 0